# permissions for end users to view mariadbs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mariadb-viewer-role
rules:
- apiGroups:
  - db8.optrin.io
  resources:
  - mariadbs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - db8.optrin.io
  resources:
  - mariadbs/status
  verbs:
  - get
